### ISSUE TITLE
Upgrade to Django 1.8

### ISSUE THREAD

**Issue by urban011** [paleocore/paleocore#121]
Upgrade in dev and resolve issues related to upgrade.

**Comment by dennereed** [comment]
See also issue #73

**Comment by PresidentNick** [comment]
Good to see the project is being upgraded to 1.8, that version is the long term support version as 1.6 isn't being supported anymore. On an unrelated note, any you guys going to Djangocon?

**Comment by dennereed** [comment]
Hey Nick, 
I’ll be out of town but Tomislav is going. You?

On July 24, 2015 at 2:15:58 PM, Nick (notifications@github.com) wrote:

Good to see the project is being upgraded to 1.8, that version is the long term support version as 1.6 isn't being supported anymore. On an unrelated note, any you guys going to Djangocon?

**Comment by PresidentNick** [comment]
I wish I could go :( I didn't get tickets before they sold out. Thought it over too much thinking my boss was going to buy them for me, but he was on vacation for a while and when he came back, they were sold out.

**Comment by urban011** [comment]
Am going to move QA to a new CentOS 7 box. This will mitigate the need to support 2.7 in parallel with 2.6 as is the case on CentOS 6

**Comment by PresidentNick** [comment]
I was able to get a ticket off the waitlist!

**Comment by dennereed** [comment]
Migration to 1.8 underway but the change breaks AJAX views of public data.

**Comment by dennereed** [comment]
Just pushed new changes to the django_update_issue#121 branch. These change address all the major issues that came up in transitioning from django 1.6 to 1.8. The big issues included:
1. broken django-olwidget library
2. problems with django migrate, needed to create migrations for all apps
3. needed to fix circularity errors in migrations between project and standard apps.
4. needed to fix DataTable view for Turkana.  
All this has been fixed in the latest commits. All unit tests pass (except lingering API tests, see issue #93) and some new unit tests have been added to better test admin views.
Next step is deploy this branch to the QA server and test it there.

**Comment by dennereed** [comment]
Launched new django 1.8 server on 21 October. This produced problems with image uploads and permissions. In production we need to explicitly define the MEDIA_ROOT in settings.py and be sure django has permissions on the media directory.

**Comment by dennereed** [comment]
Done!
