### ISSUE TITLE
Update table names in mlp and drp

### ISSUE THREAD

**Issue by dennereed** [paleocore/paleocore#55]
Currently mlp and drp have table names drp_occurrence and mlp_occurrence in the models.py file. These are the correct table names but the model names should be upated to just Occurrence. Same should be done for biology.

**Comment by urban011** [comment]
Working to standardize class names using first capital letter and camel case. One issue is that due to the class name change Django wants to rename the parent table pointer field. The only way to control the field name is to replace inheritance with a one-to-one model with the "parent" flag set to true. This is not very clean and undermines true inheritance so I'm going to go ahead and change the field names in the DB.

**Comment by urban011** [comment]
DB Changes:

ALTER TABLE drp_biology RENAME COLUMN drp_occurrence_ptr_id TO occurrence_ptr_id;
ALTER TABLE mlp_biology RENAME COLUMN mlp_occurrence_ptr_id TO occurrence_ptr_id;
ALTER TABLE drp_files RENAME TO drp_file;
ALTER TABLE drp_images RENAME TO drp_image;

**Comment by urban011** [comment]
Done, committed to github.
