### ISSUE TITLE
Project app doesn't present public data for MLP or San Francisco

### ISSUE THREAD

**Issue by dennereed** [paleocore/paleocore#80]
The ajax data table presentation of public data works for the Turkana App, but for the MLP and San Francisco apps, when made public, the table is empty. The view seems to load the data because the pagination widgets indicate the correct number of records, but the data is not presented in the table.

**Comment by wabarr** [comment]
The problem is that you need to add more fields to be displayed in the project list page. Currently, it is just showing one field.  This field is assumed to the 'id', and is being hidden, but is necessary to make each row a link to the detail page for that entry. 

If you add additional fields to display in the mlp admin, then it works.  I just pushed a commit (c72f450e298901343dac1ba7b67b515ac1ff5101) that makes explicit my assumption that the 'id' field is first.

**Comment by dennereed** [comment]
That works! Closing issue.
